---

- name: create directory for data
  file: path=~/data state=directory

- name: run redis master with docker
  shell: docker run -d -p {{redis.port}}:6379 -v ~/data:/data --name redis redis redis-server --requirepass {{redis.requirepass}} 
